### ISSUE TITLE
Option to automatically close the first tab(s) on startup

### ISSUE THREAD

**Issue by MichailiK** [igorlogius/startup-tabs#1]
**Is your feature request related to a problem? Please describe.**
When starting Firefox, the window will have both my page(s) for new windows & startup tabs open.

<img width="555" alt="Screenshot 2022-09-05 at 08 48 28" src="https://user-images.githubusercontent.com/39029839/188383149-16e608e7-83eb-4171-ad09-44d6eda7ad36.png">

I would prefer not having the tabs for new windows open on my first window.

**Describe the solution you'd like**
Provide an option to close Firefox's new window tabs.

**Describe alternatives you've considered**
1. Manually closing the tabs
2. Removing my first bookmark in Startup Tabs and use that as my homepage for new windows instead. Though I would like to have Gmail on one window & not close Gmail for every new window I open.

**Additional context**
- My personal use case for my first window is putting tabs I have constantly open, such as communications/social tabs. I open subsequent windows for each project I'm (asked to) look at or work on.
- This might conflict with other extensions opening new tabs, like some that open a tab for new updates?

**Comment by igorlogius** [comment]
Hi @MichailiK, thanks for the feedback.
 
I could see if i can add an option that would open the startup tabs in their own window. 

Would that work for you?

**Comment by MichailiK** [comment]
Yes, that'd work, as I'd also immediately open a second window for a project.

**Comment by igorlogius** [comment]
Done.

**Comment by igorlogius** [comment]
@MichailiK  fyi, 

You can access the options by clicking on the addon toolbar button (or going to the addon preferences, both works)
and after selecting a bookmark folder,  youcan test your changes by clicking on the toolbar button with your mousewheel (aka. middle/3rd mouse button).  If everything works as you want, you you can then hide/remove the addon button from the toolbar, to save some space. 

Hope you like it. Have a nive day.
