### ISSUE TITLE
Pinned tabs getting duplicated

### ISSUE THREAD

**Issue by AshKB2000** [igorlogius/startup-tabs#2]
**Describe the bug**
**Addon reopening pinned tabs**

**To Reproduce**
**1. Add a folder to the addon with #pin after the url to open them pinned
2. Close all firefox windows
3. Open the browser again and all the pinned tabs are duplicated**

**Expected behavior**
**The pinned tabs should not be duplicated**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: **Windows 11**
 - Browser: **Mozilla Firefox**
 - Version: **112.0.1**

**Smartphone (please complete the following information):**
 - Version:

**Additional context**
**What I am thinking is happening is, when I close and reopen firefox, this addon does not check if the same startup tabs are already open and opens them regardless, creating duplicates. When I open firefox with this addon active for the first time, the tabs get pinned and firefox remembers them the next time I open it, while this addon also reopens them creating duplicates.**

**Comment by igorlogius** [comment]
Making startup-tabs aware of alredy existing tabs (aka. session tabs) ... will require to delay the tab creation until all other tabs have finished loading. So the user might have to wait. Making users wait is always a risky move, so i would only propose to add an option for this, than can be enabled if you can live with that tradeoff.

**Comment by AshKB2000** [comment]
Thanks for taking a look!
Is there any temporary workaround for this?

**Comment by igorlogius** [comment]
Please update to version `1.7.10` (when it's available on AMO) 
That should help with this issue.

**Comment by AshKB2000** [comment]
Thanks for the quick update!
Though now when I reopen firefox, the first three tabs seems to get duplicated and not others.

**Comment by igorlogius** [comment]
Please share you bookmarks and addon setting, and a step by step instruction what you did so i can try to reproduce the issue.

**Comment by AshKB2000** [comment]
Here are the tabs and settings I'm using. Thanks again for the help!

![image](https://user-images.githubusercontent.com/77225873/236198696-c18f1b87-d73c-4fa5-8ca3-ef811f2699e3.png)
![image](https://user-images.githubusercontent.com/77225873/236198933-9fa4cac7-4810-4825-add7-0446b9971111.png)
![image](https://user-images.githubusercontent.com/77225873/236198997-c2c75b5d-38f2-48e2-9aec-c2666f4e81df.png)

**Comment by igorlogius** [comment]
forgot the strip the '#pin' parts of the urls ... so a comparision with an existing url would always return false ... but now it should work, if the url you bookmarks is identical to the url the tab is showing when loaded.
